#!/usr/bin/env python3
"""Package it up to move to another machine.

    python3 scripts/handover.py            package into jobbot-handover.zip
    python3 scripts/handover.py --check    only show what would go, package nothing

Taken along: the source + data/jobbot.db (every posting, score, profile and journal
entry).
NOT taken: chrome-profile (311 MB, regenerated by itself, and easily corrupted by
copying).
"""

from __future__ import annotations

import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Copied: the code, config, docs and tests — and EXACTLY one data file.
TAKE_DIRS = ["src", "scripts", "config", "docs", "tests"]
TAKE_FILES = ["run.py", "run.bat", "run-console.bat", "start.command",
              "pyproject.toml", "README.md", ".gitignore"]
TAKE_DATA = ["data/jobbot.db"]

SKIP = {"__pycache__", ".pyc", ".DS_Store", "chrome-profile", "chrome-ui"}

# --- SECRETS NEVER TRAVEL ------------------------------------------------
#
# Founding law 5: the Gmail app password and the Telegram token may live only in
# config/config.toml (chmod 600, gitignored). A zip travels by AirDrop, USB, mail
# and cloud — precisely the places a 600 file exists to avoid.
#
# TWO LAYERS, and the second is the systemic one:
#   1. block BY NAME the files already known
#   2. block BY CONTENT: any text file carrying a secret assignment.
# Layer 2 catches a secret file THAT DOES NOT EXIST YET — add config/stripe.toml
# tomorrow and forget to declare its name, and it still does not get through.
BLOCK_BY_NAME = {"config.toml"}

# A line like `app_password = "..."`. Empty values and .example files are skipped:
# an empty template is not a secret, and taking it along is the useful thing.
BLOCK_BY_CONTENT = re.compile(
    r"^\s*(app_password|password|passwd|token|api_key|apikey|secret|"
    r"client_secret|chat_id)\s*=\s*[\"']?\S", re.I | re.M)

TEXT_SUFFIXES = {".toml", ".json", ".env", ".ini", ".cfg", ".yaml", ".yml", ".txt"}


def has_secret(path: Path) -> bool:
    """Does this file carry a line assigning a secret?"""
    if path.name in BLOCK_BY_NAME:
        return True
    if "example" in path.name or "seed" in path.name or path.suffix not in TEXT_SUFFIXES:
        return False
    try:
        return bool(BLOCK_BY_CONTENT.search(path.read_text(encoding="utf-8",
                                                           errors="replace")))
    except OSError:
        return False


def wanted(path: Path) -> bool:
    return not any(s in str(path) for s in SKIP)


def collect() -> list[Path]:
    out: list[Path] = []
    for name in TAKE_DIRS:
        out += [p for p in (ROOT / name).rglob("*") if p.is_file() and wanted(p)]
    for name in TAKE_FILES + TAKE_DATA:
        path = ROOT / name
        if path.is_file():
            out.append(path)
    # THE SECRET FILTER COMES LAST, and no route skips this step.
    return sorted(p for p in set(out) if not has_secret(p))


def blocked() -> list[Path]:
    """The files that were blocked — so they can be SAID OUT LOUD, never dropped in silence."""
    o = []
    for name in TAKE_DIRS:
        o += [p for p in (ROOT / name).rglob("*") if p.is_file() and wanted(p)]
    for name in TAKE_FILES + TAKE_DATA:
        if (ROOT / name).is_file():
            o.append(ROOT / name)
    return sorted(p for p in set(o) if has_secret(p))


def human(size: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024:
            return f"{size:.0f}{unit}"
        size /= 1024
    return f"{size:.1f}TB"


def main() -> int:
    files = collect()
    total = sum(f.stat().st_size for f in files)

    db = ROOT / "data" / "jobbot.db"
    print(f"\n  {len(files)} files · {human(total)}\n")
    print(f"  DB          {'YES — ' + human(db.stat().st_size) if db.is_file() else 'NOT FOUND'}")
    for name in ("chrome-profile", "chrome-ui"):
        path = ROOT / "data" / name
        if path.is_dir():
            size = sum(f.stat().st_size for f in path.rglob("*") if f.is_file())
            print(f"  left out    {name} ({human(size)}) — it regenerates itself")

    # SAY WHAT WAS BLOCKED. Drop it silently and the user carries the package to the
    # new machine, opens the app, finds the mailbox unconnected and has no idea why —
    # and goes looking for the bug somewhere else. A block has to come with the work
    # it leaves behind.
    held = blocked()
    if held:
        print()
        for path in held:
            print(f"  NOT taken   {path.relative_to(ROOT)} — it carries a secret")
        print("  -> on the new machine: open Settings and re-enter the Gmail app "
              "password and the Telegram token.")

    if "--check" in sys.argv:
        print("\n  (--check: nothing was packaged)\n")
        return 0

    out = ROOT / "jobbot-handover.zip"
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in files:
            zf.write(path, path.relative_to(ROOT))

    print(f"\n  -> {out.name}  ({human(out.stat().st_size)})")
    print("\n  On the new machine: unzip it, install Python 3.11+ and Chrome,")
    print("  then double-click run.bat (Windows) or run python3 run.py.")
    print("  Details: docs/windows.md\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
